/*
 * Project generated by Templater
 * Argore 2024
 */


#include "Reflection/Reflection.h"
#include <iostream>


class cTest
{
	static void runTest();
};

void cTest::runTest()
{
	printf( "Ran test\n" );
}



static void doThing( int _i ); REFLECT_FUNC( doThing )
static void doSingleThing();   REFLECT_FUNC( doSingleThing )

/* impl */
void doThing( int _i )
{
	printf( "Did thing %i\n", _i );
}

void doSingleThing()
{
	printf( "no args:(\n" );
}


int main()
{
	for( auto& f : cReflectionRegistry::m_reflection_descriptors )
		printf( "%s()\n  %s (%i)\n\n", f.second.name.c_str(), f.second.file.c_str(), f.second.line );

	cReflectionRegistry::callFunction( "doThing", { "321123" } );
	cReflectionRegistry::callFunction( "doSingleThing" );

	return 0;
}